# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YixiRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YixiRN

  target 'YixiRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YixiRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'React', :path => '../node_modules/react-native'
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
